### ISSUE TITLE
Use correct terminology for strings and addresses

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-addon-dice-solver#5]
### What should we add?

What this library calls "addresses" are actually better referred to as "strings." Example:
https://github.com/Qiskit/qiskit-addon-dice-solver/blob/46c1d52fc1f9919edbb4bac1ffe704e4c553d700/qiskit_addon_dice_solver/dice_solver.py#L91-L93

The term "address" should refer to the value used to to index into a vector. As an example, for a 4e4o system, the Hartree-Fock address is 0 in the context of FCI, while the Hartree-Fock string is `0b00110011`.

**Comment by caleb-johnson** [comment]
> ### What should we add?
> What this library calls "addresses" are actually better referred to as "strings." Example:
> 
> https://github.com/Qiskit/qiskit-addon-dice-solver/blob/46c1d52fc1f9919edbb4bac1ffe704e4c553d700/qiskit_addon_dice_solver/dice_solver.py#L91-L93
> 
> The term "address" should refer to the value used to to index into a vector. As an example, for a 4e4o system, the Hartree-Fock address is 0 in the context of FCI, while the Hartree-Fock string is `0b00110011`.

This is soon to be deprecated. This function will take the bitstring matrix directly.

But your point actually has an impact on the SQD addon. There are a couple of functions in there which still handle addresses -- we should maybe deprecate those and give them better names (e.g. [bitstring_matrix_to_sorted_addresses](https://qiskit.github.io/qiskit-addon-sqd/stubs/qiskit_addon_sqd.fermion.bitstring_matrix_to_sorted_addresses.html#qiskit_addon_sqd.fermion.bitstring_matrix_to_sorted_addresses))

**Comment by caleb-johnson** [comment]
Resolution of #24 and #25 will take care of this
